### ISSUE TITLE
Bridge, crossposting tools for Publish0x

### ISSUE THREAD

**Issue by stnbu** [janraasch/hugo-bearblog#34]
I realize that bearblog is meant to be simple, which is great! I have become a constant user of bearblog.dev. It's just right for me. No muss, no fuss, no random unnecessary features!

Which brings me to my idea. I'd like to get publishing on [Publish0x](https://www.publish0x.com/) just for fun. It would be cool if I could post on bearblog, click a button and have that same content posted on Publish0x.

Of course I'm thinking in term of me doing this. I might be the only user, ever.

I'm interested in ideas anyone might have for how this might be done painlessly. For example, if there's talk of/is an API, I could help flesh that out and use it for this little project.

And if all this comes to nought, that's fine too. I always have copy and paste.

**Comment by janraasch** [comment]
Hi @stnbu,

thank you for getting in touch 🤝 😄 .

➡️ It sounds like your request should be posted over at https://github.com/HermanMartinus/bearblog/issues, which is the source code of `bearblog.dev`.

This repo here is _only_ 😇 a port of the templating to [Hugo](https://gohugo.io) which people may use for self-hosting a `bearblog.dev`-like blog.

I'll hence close this issue here.

I hope that is okay with you. Otherwise please let me know. We can always reopen 😁.

Cheers,
Jan

**Comment by stnbu** [comment]
Gotcha. Whoopsie. Thank you!
