### ISSUE TITLE
feat: pagination support

### ISSUE THREAD

**Issue by freitzzz** [janraasch/hugo-bearblog#64]
Hey @janraasch 

Not sure what's your current vision for `hugo-bearblog`, but it would be nice if there was support for pagination. What I mean by this would be to divide posts by sub-index pages on compile time, depending on how much posts exist on the folder.

For example, everyday I read and publish an article on my blog as a reference for readers, however the index page starts getting too messy while days pass by: https://joaomagfreitas.link/reads/

Let me know what are your thoughts on this, I can find some time to work on it!

**Comment by janraasch** [comment]
Hi @freitzzz, thank you for getting in touch 🤝.

The **vision** is simply to provide a self-hosted version of the original [Bear](https://bearblog.dev/) blogging platform. So this whole repo is kind of a copy & paste of https://github.com/HermanMartinus/bearblog/tree/master/templates (w/o the admin part...).

Currently we have no pagination, since there is none on the *original* template, see https://github.com/HermanMartinus/bearblog/blob/master/templates/posts.html.

You are not the first to suggest having this feature though, see https://github.com/janraasch/hugo-bearblog/issues/54.

> Let me know what are your thoughts on this, I can find some time to work on it!

I think the demand is there ☺️. Especially in your case 😁😇.

It'd be great, if you could raise this same issue on https://github.com/HermanMartinus/bearblog/. Possibly they have reasons for why they currently don't have pagination. *Or*, they might like to have it as well. If so, you could add the necessary CSS- and HTML-templating , and we just copy & paste it to this repo later on.
