### ISSUE TITLE
Are you planning to port this theme to WordPress?

### ISSUE THREAD

**Issue by huhexian** [janraasch/hugo-bearblog#75]
I really like your theme, but I'm not familiar with Hugo and I'm currently using WordPress, so I was wondering if there are any plans to develop a WordPress theme based on the bearblog theme?

**Comment by janraasch** [comment]
Hi @huhexian,

that's an Interesting idea 😁.

I would not have thought of that, since Wordpress seems like the total opposite of »bear« in the sense that it has a million features 😅.

Do you have the skills to port this theme to Wordpress yourself? The code is `MIT` licensed so you can do whatever you want with it 😊.

I am not familiar with Wordpress themes and how they work, so I'd have to look into this first. 

Is there a marketplace for Wordpress Themes where one would post this - maybe could even charge `a dollar` or `two` 💰?

Lastly, if you'd like a more Wordpress like experience, i.e. someone takes care of all the hosting, etc. and still use this theme, you can check out https://bearblog.dev/accounts/signup/.

**Comment by janraasch** [comment]
I'll close this issue, since there's been no action, since about a month.
