### ISSUE TITLE
Blog & Tags page redirects to localhost on server

### ISSUE THREAD

**Issue by rohan-kiratsata** [janraasch/hugo-bearblog#96]
The `/blog/any-post.md ` redirects to localhost on server. I have already configured `baseURL` on `hugo.toml` . I also noticed that force URL redirection seems to work, so the issue appears to be with link redirection URL. 

`hugo.toml`

```
baseURL = "https://rohankiratsata.xyz/"
theme = 'hugo-bearblog'

title = "rohan-kiratsata"
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "rohan's blog"
title = "rohan-kiratsata"
hideMadeWithLine = true
```

- I checked the `.Permalink` from `list.html` from view source as discussed on issue #18 , it's still set to localhost
![image](https://github.com/user-attachments/assets/0c8431aa-3756-4add-94e6-a1a77cd03459)

Same case with the tags page.

**Project Directory Structure** for info
```
└── 📁hugo-site
    └── .gitmodules
    └── .hugo_build.lock
    └── 📁archetypes
    └── 📁layouts
        └── 📁partials
            └── custom_head.html
    └── 📁content
        └── _index.md
        └── 📁blog
            └── new-post.md
        └── projects.md
    └── 📁public
    └── 📁themes
        └── 📁hugo-bearblog
    └── robots.txt
    └── sitemap.xml
    └── hugo.toml
    └── (other files)
           
```

Any update or fix on this?

**Comment by janraasch** [comment]
Hi @rohan-kiratsata, nice to meet you 🤝😁.

ℹ️ For these types of _usage_ issues you'll usually find (or get a response) very quickly on the `Hugo Discourse` https://discourse.gohugo.io/.

Here's something I found: https://discourse.gohugo.io/t/localhost-1313-instead-of-domain-on-subpages/51063

If building your site with `hugo` instead of `hugo server` does not work, be sure to open a new issue on https://discourse.gohugo.io. 

There are a lot of very knowledge and friendly people on there. They'll help you out in no time 🚀 ☺️.
